title: 杨芳语's Homepage
page-top-title: 杨芳语
top-section-bg-text: 探测制导与控制技术
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Yang Fangyu 2024-2026. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/Fangyu-Yang
license-link:
  text: License
  href: https://github.com/Fangyu-Yang/Fangyu-Yang.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: 杨芳语&ensp;|&ensp;Yang Fangyu
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
